### ISSUE TITLE
tensorflow errors

### ISSUE THREAD

**Issue by oscardssmith** [vladfi1/phillip#5]
I tried running `phillip --gui --human --start 0 --load agents/FalconFalconBF`, and got
`warning: already have option q_layers. skipping
warning: already have option epsilon. skipping
warning: already have option temperature. skipping
warning: already have option sarsa. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option epsilon. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option nl. skipping
warning: already have option alpha. skipping
warning: already have option actor_layers. skipping
warning: already have option critic_layers. skipping
warning: already have option epsilon. skipping
warning: already have option entropy_power. skipping
warning: already have option entropy_scale. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option user. skipping
warning: already have option netplay. skipping
warning: already have option netplay. skipping
{'clip': None, 'temperature': None, 'shield_scale': 1, 'batch_steps': 1, 'pipe_count': None, 'act_every': 2, 'tag': None, 'dump_frames': None, 'verbose': None, 'listen': None, 'delay': None, 'p1': None, 'actor_layers': None, 'audio': None, 'char': 'falcon', 'omit_char': True, 'path': 'agents/FalconFalconBF', 'cpu_thread': None, 'mute': None, 'gui': True, 'netplay': None, 'action_type': 'old', 'speed': None, 'start': 0, 'zmq': None, 'p2': None, 'fix_scopes': True, 'critic_layers': None, 'enemy': None, 'target_distance': 1e-06, 'human': True, 'reward_halflife': None, 'setup': None, 'epsilon': 0.02, 'residual_tol': None, 'enemy_reload': None, 'gpu': 1, 'sweeps': 1, 'cg_iters': 15, 'entropy_power': None, 'batch_size': 2000, 'iso_path': None, 'model': 'ActorCritic', 'dolphin': None, 'batches': 1, 'direct': None, 'entropy_scale': 0.0002, 'learning_rate': 1.0, 'alpha': None, 'natural': True, 'gfx': None, 'load': 'agents/FalconFalconBF', 'action_space': 32, 'stage': 'battlefield', 'nl': 'leaky_relu', 'player_space': 64, 'memory': None, 'fullscreen': None, 'dump_ppm': None, 'fm': None, 'experience_length': None, 'cpu': None, 'exe': None, 'xy_scale': 0.1, 'movie': None, 'q_layers': None, 'dump': None, 'user': None, 'name': None, 'sarsa': None, 'optimizer': None, 'embed_nl': False, 'tdN': 5, 'speed_scale': 1, 'iso': None, 'reload': None, 'cg_damping': 1e-05, 'cpus': None}
Creating cpu.
Using device /gpu:0
Creating model: ActorCritic
Traceback (most recent call last):
  File "/usr/local/bin/phillip", line 11, in <module>
    load_entry_point('phillip', 'console_scripts', 'phillip')()
  File "/home/oscardssmith/Downloads/phillip-master/phillip/run.py", line 63, in main
    run(**args.__dict__)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/run.py", line 27, in run
    cpu = CPU(**params)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/cpu.py", line 30, in __init__
    Default.__init__(self, **kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 20, in __init__
    self._init_members(**kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 24, in _init_members
    setattr(self, name, cls(**kwargs))
  File "/home/oscardssmith/Downloads/phillip-master/phillip/agent.py", line 27, in __init__
    Default.__init__(self, **kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 20, in __init__
    self._init_members(**kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 24, in _init_members
    setattr(self, name, cls(**kwargs))
  File "/home/oscardssmith/Downloads/phillip-master/phillip/RL.py", line 169, in __init__
    states = self.embedGame(self.input['state'])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 63, in __call__
    t = op(struct[field])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 83, in __call__
    t = self.op(array[i])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 111, in __call__
    wrapped = self.wrapper(x)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 63, in __call__
    t = op(struct[field])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 9, in nullEmbedding
    shape = tf.concat(0, [shape, [0]])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1048, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible`
Any idea what I'm doing wrong?

**Comment by vladfi1** [comment]
You're probably using too recent a version of tensorflow. You should use 0.11 (see readme).

**Comment by oscardssmith** [comment]
I am now using .11, and am getting a different error
`warning: already have option q_layers. skipping
warning: already have option epsilon. skipping
warning: already have option temperature. skipping
warning: already have option sarsa. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option epsilon. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option actor_layers. skipping
warning: already have option critic_layers. skipping
warning: already have option epsilon. skipping
warning: already have option entropy_power. skipping
warning: already have option entropy_scale. skipping
warning: already have option learning_rate. skipping
warning: already have option optimizer. skipping
warning: already have option natural. skipping
warning: already have option clip. skipping
warning: already have option target_distance. skipping
warning: already have option cg_iters. skipping
warning: already have option residual_tol. skipping
warning: already have option cg_damping. skipping
warning: already have option nl. skipping
warning: already have option alpha. skipping
warning: already have option user. skipping
warning: already have option netplay. skipping
warning: already have option netplay. skipping
{'dolphin': None, 'setup': None, 'tag': None, 'natural': True, 'omit_char': True, 'path': 'agents/FalconFalconBF', 'enemy': None, 'dump_frames': None, 'cg_iters': 15, 'human': True, 'batch_size': 2000, 'gui': True, 'experience_length': None, 'tdN': 5, 'load': 'agents/FalconFalconBF', 'zmq': None, 'clip': None, 'char': 'falcon', 'user': None, 'gpu': 1, 'iso': None, 'embed_nl': False, 'netplay': None, 'listen': None, 'player_space': 64, 'nl': 'leaky_relu', 'mute': None, 'shield_scale': 1, 'q_layers': None, 'fix_scopes': True, 'temperature': None, 'exe': None, 'actor_layers': None, 'cpu_thread': None, 'stage': 'battlefield', 'dump': None, 'speed': None, 'entropy_power': None, 'start': 0, 'residual_tol': None, 'delay': None, 'epsilon': 0.02, 'target_distance': 1e-06, 'pipe_count': None, 'name': None, 'enemy_reload': None, 'act_every': 2, 'optimizer': None, 'reload': None, 'direct': None, 'entropy_scale': 0.0002, 'cpu': None, 'p1': None, 'audio': None, 'fullscreen': None, 'cpus': None, 'sarsa': None, 'action_type': 'old', 'p2': None, 'cg_damping': 1e-05, 'fm': None, 'dump_ppm': None, 'verbose': None, 'action_space': 32, 'reward_halflife': None, 'movie': None, 'batch_steps': 1, 'model': 'ActorCritic', 'memory': None, 'xy_scale': 0.1, 'gfx': None, 'iso_path': None, 'critic_layers': None, 'sweeps': 1, 'speed_scale': 1, 'learning_rate': 1.0, 'batches': 1, 'alpha': None}
Creating cpu.
Using device /gpu:0
Creating model: ActorCritic
Traceback (most recent call last):
  File "/home/oscardssmith/smash/bin/phillip", line 11, in <module>
    load_entry_point('phillip', 'console_scripts', 'phillip')()
  File "/home/oscardssmith/Downloads/phillip-master/phillip/run.py", line 63, in main
    run(**args.__dict__)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/run.py", line 27, in run
    cpu = CPU(**params)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/cpu.py", line 30, in __init__
    Default.__init__(self, **kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 20, in __init__
    self._init_members(**kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 24, in _init_members
    setattr(self, name, cls(**kwargs))
  File "/home/oscardssmith/Downloads/phillip-master/phillip/agent.py", line 27, in __init__
    Default.__init__(self, **kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 20, in __init__
    self._init_members(**kwargs)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/default.py", line 24, in _init_members
    setattr(self, name, cls(**kwargs))
  File "/home/oscardssmith/Downloads/phillip-master/phillip/RL.py", line 169, in __init__
    states = self.embedGame(self.input['state'])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 63, in __call__
    t = op(struct[field])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 83, in __call__
    t = self.op(array[i])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 111, in __call__
    wrapped = self.wrapper(x)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 63, in __call__
    t = op(struct[field])
  File "/home/oscardssmith/Downloads/phillip-master/phillip/embed.py", line 112, in __call__
    y = self.fc(wrapped)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/tf_lib.py", line 217, in __call__
    return matmul2(x, self.weight, self.bias, self.nl)
  File "/home/oscardssmith/Downloads/phillip-master/phillip/tf_lib.py", line 176, in matmul2
    output_shape_tf = tf.concat(axis=0, values=[batch_shape_tf, [output_size]])
TypeError: concat() got an unexpected keyword argument 'axis'
` Thanks so much for the quick response, by the way.

**Comment by vladfi1** [comment]
@oscardssmith I think you modified the files.

**Comment by oscardssmith** [comment]
Thank you
